[package]
name = "bitos"
version = "0.1.0"
edition = "2024"

[dependencies]
bitut.workspace = true
bitos_core = { path = "../bitos_core" }
bitos_macro = { path = "../bitos_macro" }

[features]
zerocopy = ["bitos_core/zerocopy", "bitos_macro/zerocopy"]
