[package]
name = "bitos_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dev-dependencies]
bitos = { path = "../bitos" }

[dependencies]
proc-macro2.workspace = true
bitos_macro_core = { path = "../bitos_macro_core" }
