[package]
name = "bitos_macro_core"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2.workspace = true
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }

[features]
zerocopy = []
