[package]
name = "bitos_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitut.workspace = true
seq-macro = "0.3.5"
num-traits = "0.2.19"
zerocopy = { version = "0.8", optional = true, features = ["derive"] }
